version: '3.8'

services:
  springboot-app:
    image: springboot-one-one-mapping # Replace with your Spring Boot application image
    container_name: springboot-app
    ports:
      - "9091:9091"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/travel_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql-db

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: travel_db
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: